<?php

use PHPUnit\Framework\TestCase;

class ExampleDriveTest extends TestCase
{
    /**
     * @var Driver $drive
     */
    private $drive;

    /**
     * @var Vehicle $vehicle
     */
    private $vehicle;

    protected function setUp()/* The :void return type declaration that should be here would cause a BC issue */
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->vehicle = $this->prophesize(Vehicle::class);
        $this->drive = new Driver();
    }

    public function testGo()
    {
        $this->vehicle->startEngine()->ShouldBeCalled();
        $this->vehicle->accelerate()->ShouldBeCalled();;
        $this->drive->go($this->vehicle->reveal());
    }

}