<?php

use PHPUnit\Framework\TestCase;

final class ExampleBookTDDTest extends TestCase
{
    /**
     * @var Book $book
     */
    private $book;

    protected function setUp()/* The :void return type declaration that should be here would cause a BC issue */
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->book = new Book();
    }

    public function testGetTitle(): void
    {
        static::assertSame('A Great Book', $this->book->getTitle());
    }

    public function testGetAuthor(): void
    {
        static::assertSame('John Doe', $this->book->getAuthor());
    }

    public function testTurnPage(): void
    {
        static::assertEmpty($this->book->turnPage());
    }

    public function testGetCurrentPage(): void
    {
        static::assertSame('current page content', $this->book->getCurrentPage());
    }

    public function testGetLocation(): void
    {
        static::assertSame('Sants Street, 115', $this->book->getLocation(), 'Return the address of the Book');
    }
}