<?php

use PHPUnit\Framework\TestCase;

final class ExampleProgressTest extends TestCase
{
    /**
     * @var Progress $progress
     */
    private $progress;

    /**
     * @var File $file
     */
    private $file;

    protected function setUp()/* The :void return type declaration that should be here would cause a BC issue */
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->file = $this->prophesize(File::class);
        $this->progress = new Progress($this->file->reveal());
    }

    public function testGetAsPercentReturnFile(): void
    {
        $this->file->sent()->willReturn(100);
        $this->file->length()->willReturn(100);
        static::assertSame(100, $this->progress->getAsPercent());
    }
}