<?php

use PHPUnit\Framework\TestCase;

final class ExampleProgressDataProviderTest extends TestCase
{
    /**
     * @var Progress $progress
     */
    private $progress;

    /**
     * @var File $file
     */
    private $file;

    protected function setUp()/* The :void return type declaration that should be here would cause a BC issue */
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->file = $this->prophesize(File::class);
        $this->progress = new Progress($this->file->reveal());
    }

    public function fileDataProvider(): array
    {
        return [
            [ 100, 100, 100, "Same size of file sent as lenght, 100%"],
            [ 5, 10, 50, "Only sent 50% of file"],
            [ 3, 65, 4.6153846154, "Partial File with decimals" ]
        ];
    }

    /**
     * @dataProvider fileDataProvider
     */
    public function testGetAsPercentReturnFile($sent, $lenght, $expectedPercent, $message): void
    {
        $this->file->sent()->willReturn($sent);
        $this->file->length()->willReturn($lenght);
        static::assertSame($expectedPercent, $this->progress->getAsPercent(), $message);
    }
}